### ISSUE TITLE
Clean room implementation?

### ISSUE THREAD

**Issue by flying-sheep** [lilab-bcb/harmony-pytorch#10]
Hi, harmonypy is available under the GPL, this under BSD-3-clause.

Did you implement this completely without referring to harmonypy’s code?

cc @Intron7

**Comment by yihming** [comment]
Hi @flying-sheep ,

<del>No, we didn't.</del> Yes, you are right.

harmony-pytorch is a Pytorch implementation of Harmony algorithm (https://www.nature.com/articles/s41592-019-0619-0). The only reference we used is paper's description or pseudocode.

Moreover, the official implementation of Harmony algorithm is in R (https://github.com/immunogenomics/harmony). And harmonypy is a numpy reimplementation of its R version to my knowledge.

Hope it clarifies. And please let me know if you have further question or concern.


Sincerely,
Yiming

**Comment by flying-sheep** [comment]
Hi! Thanks for the info!

I think you wanted to write “yes we did implement it *without* referring to harmonypy’s code” in the first sentence, as the rest of your reply is an elaboration on that answer!

I’m closing this under that assumption, thank you!

PS: for later readers: the R code is also GPL-3.0

**Comment by yihming** [comment]
@flying-sheep Yes, you are right. Sorry for the confusion.
