### ISSUE TITLE
Error when using Scanpy

### ISSUE THREAD

**Issue by dmiyagi** [lilab-bcb/harmony-pytorch#7]
``Hi there, 

I have been encountering an error that I can't seem to figure out. I am using scanpy and using this on spatial data. 

`from harmony import harmonize

Z = harmonize(adata.obsm["X_pca"], adata.obs, batch_key = 'batch')`

I have adata.obs that looks like this: 
`

batch | sample | grade | GliomaType
-- | -- | -- | --
B1 | YALE-NS-0680 | 2.0 | astrocytoma
B1 | YALE-NS-0680 | 2.0 | astrocytoma
B1 | YALE-NS-0680 | 2.0 | astrocytoma
B1 | YALE-NS-0680 | 2.0 | astrocytoma
B1 | YALE-NS-0680 | 2.0 | astrocytoma
... | ... | ... | ...
B2 | YALE-NS-1209 | 3.0 | astrocytoma
B2 | YALE-NS-1209 | 3.0 | astrocytoma
B2 | YALE-NS-1209 | 3.0 | astrocytoma
B2 | YALE-NS-1209 | 3.0 | astrocytoma
B2 | YALE-NS-1209 | 3.0 | astrocytoma

<p style="box-sizing: border-box; cursor: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAARDklEQVRoQ61aCVBUV7r+7+2VhqZZRNMgiy0MbihmUF80YDRgic9l8l6NmZosT5NnOTNJLEVpIDPW60kmkVUrLpWnGSaTMUlNTEaTTHwuuKYUw1OBuI2IoLI1+9L0Rvftvq++m3eo2wSUpOZU3Wq677nnfN//f/9//nMu3M1N74kU2Bwepfju6WhbFxG9xPO8TxCECiIqNJvNHUQ0sv+Ix3/417feesuoVCq3qVSqJ/1+fzgR/UWv1+/cuHGj81GjcSMIOIiopMLYZ9BFhv3n9OnT9TzPU0tLi9DU1HTK7/dvyMvLa3nUoD/kfnFxcZJGo9lrMBgyZ8+ezbtcLrpx40afw+F4PScn578fNdZIApbKSY4jbcLAX7OysqbPnz+fBEEgp9NJp06d8jc2NlbqdLp/3bRpk+1RA4/nPsD7fL4/GY3GJ1etWkUGg0F67Pz583TlypUaURSX5OfnDzxsLEZAsvynEa1varXa1xITE4tWLl+hsZ+9Sba6Nop+cTF1e+x05swZ6uzs3CWK4vbc3Fw886ObxWLRaTSaP5hMplfT09NVoW6erAfPU+QT00gxP4EOHzlMXV1dvzGbze8+ioAd4AV1f+mZGGXo0NDQh4sWLVq6cOZc6v2wkrobm0kTE0HR65bS7dZ7VFFRgf458fHxf1q7dq3vxzIoLCz8pV6v35+RkRGSHJNALeWnyNXcTTEzEin4335Kp6sr6erVq7U6nW7Fli1brGPNAw/8F8DPKc11lJSUbIqKiirJyspSR9l4clXcpPamVvILAoUvnklRK9OovuEuHT58+I5arf7Dtm3bDv5QAhaLRanT6V4iot8uW7YsLiUlhTo+qaT+qjpSKJU0eWYSqeYn0AONk7755htvS0tLQUFBwc6xkgcnB1BcXPxzg8Fw6NlnnyXtt50k/MNK7Q9ayOseIl6tpNhfLyeF0UC1tbV06dIlcrvdPzOZTMfWrl3rGQ8RgNdoNC+pVKrSZcuW6ZOSkki4300P3jlKvFZFOoOeoiYbSTE7hlxJYfTH8nK3KIo5D5NRAIGioqK/JCUlvbBixQryH71JYq+TuprayOV0kugRKChhIsW9uoIGHIN07do1qqmp6fB6va85nc4jFotFYCSKi4unKpVKzmazNVosFj9+t1gsaq1WuyQ4OPj9lJQUY1paGqmG/NS09xgJ/Q4S/X4KN04kfbiBlEkTSbHQRIe/+JwaGhr2G43GzevXr3ePZqRhAsXFxalBQUEXsrOzgxMSEsj98f8SN+SjntYO8qhIIuD3eCnsX5Jp4up5Umb6+uuvxWvXrnUT0SmNRrPF7Xb/guO4uTzPL1QqlYNut7tFqVRe4Xn+zx6PZ5dGo3kyOTl50uLFi0kXFESdX1wm14NOct3vJNUEPYVqQyhYH0KKhEjSLEmmW/V1iANrU1NT+vbt2xseSqCkpOT58PDwg3PnzqXU1FRyvV9JnEjU1WyloaEh0sZFUmhaInUdvUKTX8qkoPgounPnDkhQeHg4NTU1WfV6Pa/VaiepVCoKDQ0lURTp1q1bdpVK1ZGUlDS1paWFFixYQHPmzKGhtl7qOl5Nok+U5OmobyNDaCiFhBmIjwkjbeYMqr11HQTEnp6ejPz8/AtjErBYLFqdTvd7rVZrXr58OSWaTOQsv0icWkX97kHyKzlShetJPzeBhEE3eXsHKXJJikTs3r179NhjjyHl0cDAAMF7fX19FBQURBEREXT58mWaPHmy9B39IyMjJXJ9l+qII46IJ4mMp2uQ1JyC9LyauIl60mbNoNv37sJAvv7+fnN+fj4C+XtNklBxcfHjCoXiSHp6etzUqVMp3BBGzvcvki9UQ7YBGwUlRJF+ToJkUXWknvxDAimCNdJ3v99PWK05jpO+41Pe2G/oh0uhUEh9BIebOJ4nYcBJHE80UH1PklKkcSLxHE/aZTOozzkID8IIgz6fzzja2iPNVlRUpCeiCyaTaXZWVpbkSscfL5DdYSchQkuqCD1FpM8gpUH3PQt4vV7y+XzSBWBKpVL6G6QAGL/hO4jodDrp95FNGHRS79mb5Om2EW+1U0SqiTRPTyO7100nTpyg+/fvn8nNzc0cLZUyAtOVSuWJKVOmxM6ePZvgBccHleRSiaRNjaOQ6bEEb7PGAMGaKDXcbrcEDH8DMIBL3lKrCQRxD8QQG3iGeU1Oxu8VyFZzj1zfNlFEvJHUT/2EWjqsdOHCBbJarf11dXUTDxw44B1JXoK1e/dujcfj+Uyj0azMyMggLC6uT66Qy+chMSqYIrPmBEgDBKBnXADFwAMYtO7xeCQCuIdspdVqh0GDJIjhYtIDBp/DTT1nrhP1uchgnEDqJcl08/Y/6Ny5c+RyufaZzebXxvQACDgcjoupqak/hQeio6NJaOolfkIIkVY5THqk+wcHByWgsC7TPj4BDiRRWYIQiIEsmhw8Gxj30aQ4cnpIHHSTYlIodXZ1UWVlJTU2Nn6xdevWn40ZxLt37w51u91/i4uLy5w3bx5NmTKFfG0DJKg58um+AwfwGo0mwBNM4yDByMkDWf43CEE+IwMd30GOyU7h8ZHK5SdFdBi0LxGwWq2Htm3b9uzD0mioTqer0Ov181HWwgPQll/8bu8ity7LPPhdLoHRBh/tt9Gex29o330ik32X1axWKx07doy6u7uP5uXlrRyTALKQ1+s9v2rVqrmoyWNjY6XBYBkEKCwXHBwsWYkFMBsM91gcPIwEnoX+5c+zrAVDOBwO6R68jAvjNjY2UltbGxaz05s3b0YW+l4bXgfUavXfFy1aFA3rY2FimmUalwLNN3b1DBKIBdZP/hyAIxuN1ZgnWSpGP5DA4tjQ0ICqdECj0Ux+5ZVXUMoHNIlAaWlptlqt/jA2NjYiOztbehgTwiosCPEdIMdqLG3CqsxrCFhY/mHgMZ58bAS+Xq+X5rLb7ZKEmpub7RzHxefk5PSOSmDnzp0x2Lg/8cQT0xctWiSlQYAAeJCAN7D8y1dZ9GEpEmkSBHDB9eiPvnge48AzuIexQAhyRD/W2D0QxmLHshc8c/HiRaqqqqrw+/0/H217ye3bty/E6XSWpqWlvZyRkSFpgEkFtQ2AYlC5zjs6Oujjjz+mBw8e0KRJk+jFF18ko9EoaRz9AAANwAGCAfnqq6+ksVEsPvfcc8MGYfHGDBISEiLdAyEYA1vZ2tra/R6PZ7PFYgkoq7m333572tSpU7/JysoyoKpk2aC/v1+amMmIEcBkAI9CraSkhHp6eghe279/v9SXeQlkWN1js9lo586dEvA333xTmuOdd94hlC0sfcJTuCAfjAEvYX7Mh1j47LPPrE6n85nc3NwquYy4wsLCFJ7nz61evToiOTl5mAAsBRLMA8ya+L5nzx6p4jx+/Lg0GSRUVVUlaRnPoS8IsNW4pqaGcnJyaNasWdKJA+S4bt062rBhg9QffUEEngNpGFIebydPnsQGqo3n+ZVbt26tCSBQVFS03mg0lj/zzDMcXMcawAMAq2XgTgBjeu/s7JS2lbAYXI8yHA0AWL3DKlCQPXr0qLRAwgCPP/44RUVFDccFC2R4AGkchOQxBykfPHjQ6XQ6N+Xl5ZUHECgrK9uTmpr6KmoglgYBGm4HELaC4jMsLCwg+JjcWCnNBmYpGNksYLIRpTaLt97e3oBVmq07DA+kWVVV5bt06dIOQRB+L9++cmVlZe3x8fGTMjMzhw+WYH0ELh4EGVgSGxG5W+WrJwjIMxSkAMJyj7IsNbIvSMDiiCWWvqF/NGBAgwc++OADkef5v9vt9nUFBQV9zDCIgdfi4uJ2rFmzJhgPYCIMCCvC3WgAAgnJ0x7TLQOG+6yUhhTQIDfmRVZqM5kx68q9huKQldys6GNe2rVrV7/f73/V5XJ9EuCB7du3z0lLS7ucnZ2tYhYGcBCAFaFFeRXKijHmAWZBSA5SeO+996iurk7CNWPGDNq6datEArEiz/2j7eDgaXgf5GBMOcny8vKuvr6+tbm5uecCZLljx47MlJSUChxzIKczQFgFsRDBEgALMpATrConBMviQqrbvHkzCi+aOXOmNPnVq1eldPjRRx9JhsBvchIYE96CdNh6wSoAOWFUpdXV1f13795dn5eX93kAAaRRrVZ7PD09PRqnBczl0B1yPayCvwGcTRQQmf+v4dbWVnr55Zcl0lI1y3FSOYxs9emnn0qbfTl4NgbGBwkYgS1gMB48wLLZkSNHME693W5fazabawMI7Nq1K0wUxT8vXLhwDQI1MTFxuD4HGEiDFWryjctIEtAvln1IBn8DGKx44MABKW2ywBz5HEu1SMWYB3MiCcDzIHDz5k0pmZw8efKUz+fLlusfY3FFRUXRYWFhnw8MDKQ9//zzHPIwS38YAJpkOywMPjL4GCDIASAQBxs3bpSsidUX0hkZR3ISsDwszuYAaXYogHuQYX19vdjR0fGt1+vNfP3113sCPIDtpMvlyuZ5vtRoNE7FaongYwEN+bByF4RAYrTGto3oi7Oi9vZ2QlyxBXC00wiMw/YBkBzGZ6kT93Bo1tDQ4O/t7T3j9/vLzGbziZH7YnbWAE/8hIh+ZTKZfoPTafaygQGDWzH4yG2lnAzLUNXV1VKpsXTpUun2yLMiuf4RtJAcPMbGZpuevXv32gVBKBRFsdxsNrePZriAU6g33nhjTkpKSlVcXJwGR4xsclaVokYBIbYmsHoJbme/ISD37dtH06ZNkwgwj8EAkArijHkD4GF1VLcwDisfIJ0bN27Q9evXu1pbW39RUFBwZlS3wzjyG4WFhU8GBwefmjdvngZZA2BRJkPbbGMCQKweAqjTp09LZTVIAEB9fb0UtCB3+/Ztqf5BakVfk8lES5YsGbY0GxfrDoIcRkDSgPdQHNrt9p7e3t5fms3mk+MisH//fl1fX9+mxMTE38XHxwdDEjilwCesx/a/+GT5mwUuDm7RB4Bx7g9QINPc3Cyl45iYGOmT1fgADEuDGCTGyg4cJWIzj2dtNtsalUpVkZOT890GY5QWeJBJRGVlZbEul+t/srKyZrEUihNlWB0NZAAeQNjkLFDH0jorT9imHlpnZTpbkZuamqSxsQeGx6xW65ktW7Y8PRZw9vv3COBGUVHRarVa/buoqKjpoaGhIVihsRlBZsIkbMsHi8OS+AQoVsfIJ2WneGzPDN1DhogrJAoQQBBfuXJFqgSOHz/u5nn+vNvtxqulgNp/XB5AJ4vFwuv1+hiv1/vbWbNmbWhra+OhXcQDgo2VGbAiwEBGSIeIAfn5J8aCt3CPBToLXHgXSQHEEEfoB+23tbXtFkXxDY/H08fe7jzMC6N6gD2AV0U+n2+vUqlMVqvVUU899VQI9Im9A9u4wIIAxcoNZBi2sYdXEPyw8IQJE4ZLA/THBb2DwNmzZwfVanWHz+erdrlcL1gslnG9c5Oy5KM0hndber1+kiAI/x4WFvYrhUKRjCDFggeLs/qGld9s/wDg7IAKXmGrOySFugkVa19f31B7e/t9QRDe8vl8p81ms5Xj8F5o/O2RBNhQhw4dUjc2Nj6mUCjyiWjDggULlNgWotTAG332HgCeQFBDEgh8XKz8wAIHYgjY5ubmIUEQ9giC8O7Q0ND98chl3DHwMP6ID4PBMNvhcOyJj49PUavVupiYGBVO83DJCz52oIXSAmnyyy+/FEJDQ21dXV21oij+xz/j/y7G7YGRpEpLSyd4vd7FHMc9bTKZXuju7g4BAWQlgEWGQSGGwEdd5Pf77e3t7QeICKvqhUf9D8R4RfSjCbAJcDBms9nwhmcKx3G/5jhOxXGcked5pdfrvaNSqYI9Hs8Bv99fo1ar7zxsURovaHm//wM527m4N+gkTgAAAABJRU5ErkJggg==&quot;) 0 0, auto; margin: 1em 0px 0px; text-align: left; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">35463 rows × 4 columns</p>

`
and has 35463 rows × 4 columns

my adata object looks like this: 
AnnData object with n_obs × n_vars = 35463 × 36601
    obs: 'batch', 'sample', 'grade', 'GliomaType'
    uns: 'log1p', 'neighbors', 'pca', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
    
    
you can see that the n_obs matches in both cases; however, I get this error when using any other column than "sample"

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[82], line 5
      1 from harmony import harmonize
      3 #data_np =  df.to_numpy()
----> 5 Z = harmonize(adata.obsm["X_pca"], adata.obs, batch_key = 'batch')

File /gpfs/ysm/project/gunel/dfm42/conda_envs/spatial_2023_2/lib/python3.8/site-packages/harmony/harmony.py:144, in harmonize(X, batch_mat, batch_key, n_clusters, max_iter_harmony, max_iter_clustering, tol_harmony, tol_clustering, ridge_lambda, sigma, block_proportion, theta, tau, correction_method, random_state, use_gpu, n_jobs, verbose)
    137 N_b = torch.tensor(
    138     batch_codes.value_counts(sort=False).values,
    139     dtype=torch.float,
    140     device=device_type,
    141 )
    142 Pr_b = N_b.view(-1, 1) / n_cells
--> 144 Phi = one_hot_tensor(batch_codes, device_type)
    146 if n_clusters is None:
    147     n_clusters = int(min(100, n_cells / 30))

File /gpfs/ysm/project/gunel/dfm42/conda_envs/spatial_2023_2/lib/python3.8/site-packages/harmony/utils.py:23, in one_hot_tensor(X, device_type)
     21 n_col = X.cat.categories.size
     22 Phi = torch.zeros(n_row, n_col, dtype=torch.float, device = device_type)
---> 23 Phi.scatter_(dim=1, index=ids, value=1.0)
     25 return Phi

RuntimeError: index -1 is out of bounds for dimension 1 with size 3` 

Harmony runs fine when using the "sample" column, but not with any other column. I need it to work with the "batch" column. the only thing I can think of is that the "sample" column is the only one that has a different value per sample wheres the others are shared i.e. I only have 3 batches for 11 samples but of course there are 11 sample names for 11 samples. 

I have attached a file that has what's loaded into my environment. 

thanks in advance

[reqs.txt](https://github.com/lilab-bcb/harmony-pytorch/files/10636312/reqs.txt)

**Comment by dmiyagi** [comment]
I realized that my metadata file had an issue where the batch ID was not assigned to all the cells correctly. Once I fixed this I was able to resolve the issue. Sorry, I thought I had checked for all the possible issues like this before opening this request.

**Comment by yihming** [comment]
@dmiyagi Glad to hear that you figured out the issue by yourself. 

To help improve the error message in future use, may I know more specific about your issue? Is it because not all the cells have batch IDs associated?

**Comment by dmiyagi** [comment]
> 

Hi @yihming sorry for the late response! Yes that is what happened. there were some blanks in the "batch" which caused the error, which wasn't true for the "sample" column. 

I do have another question, which I'm happy to start with another thread, but if I'm wanting to pass the 'X_harmony" array downstream to other scanpy external packages like scanpy.external.pp.magic (https://scanpy.readthedocs.io/en/stable/generated/scanpy.external.pp.magic.html) or scanpy.external.tl.phate (https://scanpy.readthedocs.io/en/stable/generated/scanpy.external.tl.phate.html) how would I convert it to take the place of adata.X? sort of like how correct_scanpy() works in Scanorama (https://github.com/brianhie/scanorama) ? Thank you!!


I
